console.log("Hello, World!");
console.log("This is a simple JavaScript program.");
console.log("It prints messages to the console.");
console.log("I am a new learner in JavaScript and excited to learn more!");
let name = "Prajeet";
let age = 25;
console.log(name);
console.log(age);
const pi = 3.14159;
console.log(pi);
let a = 10;
let b = 5;
console.log(a+b);
console.log(a-b);
console.log(a*b);
console.log(a/b);
console.log(a%b);